version: '2'

tasks:
  build:
    cmds:
      - go build -o dist/cocosmail

  run:
    deps: [build]
    dir: dist
    cmds:
      - source conf/cocosmail.cfg && ./cocosmail

  builddist:
    deps: [build]
    cmds:
      - zip -r cocosmail.zip dist/conf/cocosmail.cfg.base
      - zip -r cocosmail.zip dist/ssl
      - zip -r cocosmail.zip dist/tpl
      - zip -r cocosmail.zip dist/run
      - zip -r cocosmail.zip dist/cocosmail

  deploy:
    deps: [build]
    cmds:
      - rsync dist/cocosmail root@51.15.212.212:/home/cocosmail/dist/cocosmail
      - ssh root@51.15.212.212 setcap cap_net_bind_service=+ep /home/cocosmail/dist/cocosmail
      - ssh root@51.15.212.212 systemctl restart cocosmail